# Generated by Django 4.2.5 on 2023-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrineStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='urine_strips/')),
                ('colors_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
